export const DailyTasks = [
  {
    id: 1,
    title: "Update inventory records",
    description: "Verify and update stock levels in the system for Warehouse A",
    priority: "high",
    status: "in progress",
    assigned_to: ["op101"],
  },
  {
    id: 2,
    title: "Send daily sales report",
    priority: "medium",
    status: "pending",
    assigned_to: ["op102", "op103"],
  },
  {
    id: 3,
    title: "Resolve delivery delay complaints",
    description:
      "Check and respond to 4 unresolved customer queries from yesterday",
    priority: "high",
    status: "pending",
    assigned_to: ["op104"],
  },
  {
    id: 4,
    title: "Reconcile bank transactions",
    priority: "low",
    status: "completed",
    assigned_to: ["op102"],
  },
  {
    id: 5,
    title: "Schedule pickup for returns",
    description: "Coordinate with courier for 6 return pickups today",
    priority: "medium",
    status: "in progress",
    assigned_to: ["op101"],
  },
  //   {
  //     id: 6,
  //     title: "Generate employee attendance report",
  //     priority: "low",
  //     status: "completed",
  //     assigned_to: ["op105"],
  //   },
  //   {
  //     id: 7,
  //     title: "Backup CRM database",
  //     description: "Weekly backup task",
  //     priority: "high",
  //     status: "pending",
  //     assigned_to: ["op106"],
  //   },
  //   {
  //     id: 8,
  //     title: "Organize meeting with vendor",
  //     priority: "medium",
  //     status: "in progress",
  //     assigned_to: ["op104", "op103"],
  //   },
  //   {
  //     id: 9,
  //     title: "Clean and maintain warehouse equipment",
  //     priority: "low",
  //     status: "completed",
  //     assigned_to: ["op107"],
  //   },
  //   {
  //     id: 10,
  //     title: "Respond to internal audit checklist",
  //     description: "Ensure all compliance items are ready",
  //     priority: "high",
  //     status: "pending",
  //     assigned_to: ["op105"],
  //   },
  //   {
  //     id: 11,
  //     title: "Refresh product pricing",
  //     priority: "medium",
  //     status: "in progress",
  //     assigned_to: ["op102"],
  //   },
  //   {
  //     id: 12,
  //     title: "Check for duplicate entries in order log",
  //     priority: "low",
  //     status: "pending",
  //     assigned_to: ["op101"],
  //   },
  //   {
  //     id: 13,
  //     title: "Team performance feedback form distribution",
  //     priority: "low",
  //     status: "completed",
  //     assigned_to: ["op106"],
  //   },
  //   {
  //     id: 14,
  //     title: "Compile customer satisfaction survey results",
  //     description: "Analyze responses from the previous month",
  //     priority: "medium",
  //     status: "in progress",
  //     assigned_to: ["op107"],
  //   },
  //   {
  //     id: 15,
  //     title: "Test emergency alert system",
  //     priority: "high",
  //     status: "pending",
  //     assigned_to: ["op105", "op106"],
  //   },
];

// export const DailyTasks = []