export const NewTasks = [
  {
    id: 1,
    title: "Update inventory records",
    description: "Verify and update stock levels in the system for Warehouse A",
    priority: "high",
    status: "in progress",
    assigned_by: "ad101",
    due_date: "2025-07-14",
    assigned_to: ["op201", "op202"],
  },
  {
    id: 2,
    title: "Send daily sales report",
    priority: "medium",
    status: "pending",
    assigned_by: "ad102",
    due_date: "2025-07-14",
    assigned_to: ["op203", "op204", "op205"],
  },
  {
    id: 3,
    title: "Resolve delivery delay complaints",
    description:
      "Check and respond to 4 unresolved customer queries from yesterday",
    priority: "high",
    status: "pending",
    assigned_by: "ad104",
    due_date: "2025-07-15",
    assigned_to: ["op206"],
  },
  {
    id: 4,
    title: "Reconcile bank transactions",
    priority: "low",
    status: "completed",
    assigned_by: "ad102",
    due_date: "2025-07-15",
    assigned_to: ["op207", "op208"],
  },
  {
    id: 5,
    title: "Schedule pickup for returns",
    description: "Coordinate with courier for 6 return pickups today",
    priority: "medium",
    status: "in progress",
    assigned_by: "ad101",
    due_date: "2025-07-16",
    assigned_to: ["op209"],
  },
  {
    id: 6,
    title: "Generate employee attendance report",
    priority: "low",
    status: "completed",
    assigned_by: "ad105",
    due_date: "2025-07-16",
    assigned_to: ["op210", "op211"],
  },
  {
    id: 7,
    title: "Backup CRM database",
    description: "Weekly backup task",
    priority: "high",
    status: "pending",
    assigned_by: "ad106",
    due_date: "2025-07-17",
    assigned_to: ["op212"],
  },
  {
    id: 8,
    title: "Organize meeting with vendor",
    priority: "medium",
    status: "in progress",
    assigned_by: "ad104",
    due_date: "2025-07-17",
    assigned_to: ["op213", "op214"],
  },
  {
    id: 9,
    title: "Clean and maintain warehouse equipment",
    priority: "low",
    status: "completed",
    assigned_by: "ad107",
    due_date: "2025-07-18",
    assigned_to: ["op215", "op216", "op217"],
  },
  {
    id: 10,
    title: "Respond to internal audit checklist",
    description: "Ensure all compliance items are ready",
    priority: "high",
    status: "pending",
    assigned_by: "ad105",
    due_date: "2025-07-18",
    assigned_to: ["op218"],
  },
  {
    id: 11,
    title: "Refresh product pricing",
    priority: "medium",
    status: "in progress",
    assigned_by: "ad102",
    due_date: "2025-07-19",
    assigned_to: ["op219", "op220"],
  },
  {
    id: 12,
    title: "Check for duplicate entries in order log",
    priority: "low",
    status: "pending",
    assigned_by: "ad101",
    due_date: "2025-07-19",
    assigned_to: ["op221"],
  },
  {
    id: 13,
    title: "Team performance feedback form distribution",
    priority: "low",
    status: "completed",
    assigned_by: "ad106",
    due_date: "2025-07-20",
    assigned_to: ["op222", "op223"],
  },
  {
    id: 14,
    title: "Compile customer satisfaction survey results",
    description: "Analyze responses from the previous month",
    priority: "medium",
    status: "in progress",
    assigned_by: "ad107",
    due_date: "2025-07-20",
    assigned_to: ["op224"],
  },
  {
    id: 15,
    title: "Test emergency alert system",
    priority: "high",
    status: "pending",
    assigned_by: "ad105",
    due_date: "2025-07-20",
    assigned_to: ["op225", "op226"],
  },
];
